language: python

notifications:
#  email: 
#    recipients: 
#      - "nupic-hackers@lists.numenta.org"
#    on_success: change
#    on_failure: change
  webhooks: "https://webhooks.gitter.im/e/68f77bae61efa5c931f8"

env:
  global:
  - NUPIC=$TRAVIS_BUILD_DIR/nupic
  - PYTHONPATH=/home/travis/build/numenta/nupic/lib/python2.7/site-packages:$NUPIC
  - AWS_ACCESS_KEY_ID=AKIAIGHYSEHV3WFKOWNQ
  - secure: BqIdU+D/Vtt5tydjKc1jxc9tHHu8rK9WIv4VysJD++vRSLERYhaSI3Gy1pjB5rrc/VfdLAqWmC7YdmTwEudyVtl0niUF5Zdtztq777qWK2PCxQBUAAXBqaYKNmHDXaBO0I63oTrfevM6OD7UspHqbBzfJhU9RF9GYSy7mz9cvYM=

before_install:
  # Upgrade pip
  - pip install --upgrade pip
  # Wheels is currently used for installation.
  - pip install wheels
  # These are required for the fetch_wheels.py script.
  - pip install requests
  - pip install boto


install:

  - echo $PYTHONPATH
  - echo $NUPIC
  - NUPIC_SHA=`cat nupic_sha.txt`
  - 'echo NUPIC SHA: $NUPIC_SHA'

  # Fetches the binary distribution.
  - travis_retry python fetch_wheels.py

  # Install wheels we just downloaded.
  - NUPIC_VERSION=`python -c "import nupic; print nupic.__version__"`
  - echo "Installing NuPIC ${NUPIC_VERSION} with wheels..."
  - pip install --use-wheel --no-index --find-links=wheelhouse nupic==${NUPIC_VERSION}

  # Clone nupic to get the tests
  - git clone https://github.com/numenta/nupic.git
  - (cd nupic && git reset --hard ${NUPIC_SHA} && rm -rf nupic)

script:

  # NuPIC swarming tests
  - cd $NUPIC
  - . ./run_tests.sh -w

  # NuPIC example runs
  - . ./ci/travis/script-run-examples.sh

  - cd $TRAVIS_BUILD_DIR

  # Regressions tests
  - py.test tests/
