language: python

env:
    global:
        - export NUPIC=$TRAVIS_BUILD_DIR

install:
    - NUPIC_SHA=`cat nupic_sha.txt`
    - printf "\n*********\nRunning NuPIC regression tests against:\n\thttps://github.com/numenta/nupic/tree/${NUPIC_SHA}\n*********\n"
    - pip install requests
    - pip install nose
    - python install_from_archive.py
    - travis_retry pip install -q -r nupic-linux64-${NUPIC_SHA}/requirements.txt
    - export NTA=`pwd`/nupic-linux64-$NUPIC_SHA
    - export NTA_CONF_PATH=$NTA/conf/default
    - export PYTHONPATH=$PYTHONPATH:$NTA/lib/python2.7/site-packages

script: 
    - nosetests
