language: python

env:
  global:
  - NUPIC=$TRAVIS_BUILD_DIR
  - PYTHONPATH=/home/travis/build/numenta/nupic/lib/python2.7/site-packages:$PYTHONPATH
  - AWS_ACCESS_KEY_ID=AKIAIGHYSEHV3WFKOWNQ
  - secure: BqIdU+D/Vtt5tydjKc1jxc9tHHu8rK9WIv4VysJD++vRSLERYhaSI3Gy1pjB5rrc/VfdLAqWmC7YdmTwEudyVtl0niUF5Zdtztq777qWK2PCxQBUAAXBqaYKNmHDXaBO0I63oTrfevM6OD7UspHqbBzfJhU9RF9GYSy7mz9cvYM=

install:
- echo $PYTHONPATH
- NUPIC_SHA=`cat nupic_sha.txt`
- 'echo NUPIC SHA: $NUPIC_SHA'
# These are required for the fetch_egg script.
- pip install requests
- pip install boto
# These are the required python dependencies for NuPIC
- travis_retry pip install -q -r  /home/travis/build/numenta/nupic/external/common/requirements.txt
# Fetches the binary distribution.
- python fetch_binary.py
# Unpacks the distro into the Travis-CI file system
- sudo tar zxvf nupic-archive.tar.gz -C /

script:
- py.test tests/
