language: python

env:
    global:
        - export NUPIC=$TRAVIS_BUILD_DIR

notifications:
    email:
        - nupic-hackers@lists.numenta.org

install:
    - NUPIC_SHA=`cat nupic_sha.txt`
    - "echo NUPIC SHA: $NUPIC_SHA"
    - pip install requests
    - python install_from_archive.py
    - travis_retry pip install -q -r nupic-linux64-${NUPIC_SHA}/requirements.txt
    - export NTA=`pwd`/nupic-linux64-$NUPIC_SHA
    - export NTA_CONF_PATH=$NTA/config
    - export PYTHONPATH=$PYTHONPATH:$NTA/lib/python2.7/site-packages

script:
    - py.test tests/
