language: python
env:
  global:
  - NUPIC=$TRAVIS_BUILD_DIR
  - AWS_ACCESS_KEY_ID=AKIAIGHYSEHV3WFKOWNQ
  - secure: bb3tUZZc17mhUzCFTvuiE4b8ZCaa5rrnGdGZweLFlR7Ukx1UXNnpjGoBSR4opOR+1tWr9inMXkNCw2k6vbtXDmxiI+7oT7CUA7C8dPt4SgJ1kwLWS1UhdQZXZPZhKskraf+cMXPjffhEGxuHvqq8uQvdKG6KTY5hSsdXgZTJTgE=
install:
- NUPIC_SHA=`cat nupic_sha.txt`
- echo $AWS_ACCESS_KEY_ID
- 'echo NUPIC SHA: $NUPIC_SHA'
- pip install requests
- pip install boto
- python fetch_egg.py
- pip install nupic-archive.tar.gz
script:
- py.test tests/
