language: python
env:
  global:
  - NUPIC=$TRAVIS_BUILD_DIR
  - AWS_ACCESS_KEY_ID=AKIAIGHYSEHV3WFKOWNQ
  - secure: XdafgrSdTfBcfCS1QOybf3IabkxXaIrRkyEd3Tnii4QjB4pqPplBF2VMo1CfVDqFS0z3c6KrV9JhssYYDUZReYZuSA2xRCe9tdn8nw+qLXj5XdfAlXOH6fm/StD5RuRFFD0DrQycD4VOB9QinyHpkHsxI35X0mYBR4z4TXVlMMg=
install:
- echo $TRAVIS_SECURE_ENV_VARS
- NUPIC_SHA=`cat nupic_sha.txt`
- echo $AWS_ACCESS_KEY_ID
- 'echo NUPIC SHA: $NUPIC_SHA'
- pip install requests
- pip install boto
- python fetch_egg.py
- pip install nupic-archive.tar.gz
script:
- py.test tests/
