language: python

env:
    global:
        - export NUPIC=$TRAVIS_BUILD_DIR

#notifications:
#    email:
#        - nupic-hackers@lists.numenta.org

install:
    - NUPIC_SHA=`cat nupic_sha.txt`
    - "echo NUPIC SHA: $NUPIC_SHA"
    - pip install requests
    - python install_from_archive.py
    - pip install nupic-archive.tar.gz

script:
    - py.test tests/
